### ISSUE TITLE
Backport Feb'24 changes from adt

### ISSUE THREAD

**Issue by verdimrc** [aws-samples/playground-persistent-cluster#11]
- [ ] aws-samples/awsome-distributed-training#159
- [ ] aws-samples/awsome-distributed-training#161
- [ ] aws-samples/awsome-distributed-training#162
- [ ] aws-samples/awsome-distributed-training#163
